version: "3"

services:
  
  nginx: 
    image: mapic/shiny-nginx:latest
    env_file: config/nginx.env
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx.certbot.conf:/etc/nginx/nginx.certbot.conf
      - ./ssl/:/home/ssl/
    ports:
      - "80:80"
      - "443:443"
    logging:
      options:
        max-size: "5k"
        max-file: "10"
    command: "bash docker-entrypoint.sh"

  auth0:
    image: mapic/auth0-express:latest # closed, authenticated
    # image: mapic/auth0-express:open # open, no authentication
    env_file: config/auth0.env
    restart: unless-stopped
    volumes:                              
      - shiny-logs:/usr/src/logs
      - ./config/auth0.env:/home/app/.env
      - ../auth0-express/app/:/home/app     # dev mode
      # - ../auth0-express/open-app/:/home/app     # open, no authentication
    command: "npm start"                    
    environment: 
      DEBUG: "true"

  shiny:
    image: mapic/shiny-server:latest
    env_file: config/shiny.env
    restart: unless-stopped
    logging:
      options:
        max-size: "20k"
        max-file: "10"
    volumes:
      - ./config/shiny-server.conf:/etc/shiny-server/shiny-server.conf
      - shiny-logs:/var/log/shiny-server/
      - shiny-data:/srv/shiny-server/apps # shiny data volume shared with sftp folder

  sftp:
    image: mapic/sftp:latest
    restart: unless-stopped
    volumes:
        - shiny-data:/home/shiny/upload # shiny data volume shared with shiny
        - shiny-logs:/home/shiny/upload/logs
        - ./config/sftp.users.conf:/etc/sftp/users.conf:ro
    ports:
        - "2222:22"

networks:
  default:
    external:
      name: shiny-network  

volumes:
  shiny-data:
  shiny-logs: